name: tomoenv
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tomopy
 
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - h5py
    - scipy
    - opencv-python
    - porespy
    - git+https://github.com/aniketkt/ImageStackPy.git#egg=ImageStackPy
    - git+https://github.com/aniketkt/CTSegNet.git#egg=ct_segnet
    - git+https://github.com/aniketkt/TomoTwin.git@master#egg=tomo_twin

